A_Main/urls.py
from django.urls import path
from . import views
app_name = "Main"

urlpatterns = [
    path('', views.index, name="index")
]

A_app/urls.py
from django.urls import path
from . import views

app_name = "contenido"

urlpatterns = [
    path('discos/', views.discos, name="discos"),
    path('agg_disco/', views.nuevo_disco, name="agg_disco"),
    path('libros/', views.libros, name="libros"),
    path('agg_libro/', views.libro_nuevo, name="agg_libro"),
    path('remeras/', views.remeras, name="remeras"),
    path('agg_remera/', views.remera_nueva, name="agg_remera"),
    path('resultados/', views.busqueda_discos, name="resultados")
]

B_proyecto/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    # path('admin/', admin.site.urls),
    path('', include("A_Main.urls")),
    path('cont/', include("A_app.urls")),
]

A_Main/models.py
from django.db import models

# Create your models here.

A_app/models.py
from django.db import models


# Create your models here.
class Disco(models.Model):
    nombre = models.CharField(max_length=100)
    artista = models.CharField(max_length=100)
    year = models.IntegerField()

    def __str__(self):
        return f"{self.nombre} - {self.artista}"


class Remera(models.Model):
    disenio = models.CharField(max_length=100)
    talle = models.CharField(max_length=6)

    def __str__(self):
        return f"{self.disenio} - {self.talle}"


class Libros(models.Model):
    autor = models.CharField(max_length=100)
    titulo = models.CharField(max_length=100)
    year = models.IntegerField()

    def __str__(self):
        return f"{self.autor} - {self.titulo}"

A_app/forms.py
from django import forms
from .models import Disco, Remera, Libros


class DiscoForm(forms.ModelForm):
    class Meta:
        model = Disco
        fields = ["nombre", "artista", "year"]


class LibroForm(forms.ModelForm):
    class Meta:
        model = Libros
        fields = ["autor", "titulo", "year"]


class RemeraForm(forms.ModelForm):
    class Meta:
        model = Remera
        fields = ["disenio", "talle"]

A_Main/views.py
from django.shortcuts import render


# Create your views here.

def index(request):
    return render(request, "A_Main/index.html")

A_app/views.py
from django.shortcuts import render, redirect
from .models import Disco, Remera, Libros
from .forms import DiscoForm, LibroForm, RemeraForm


# Create your views here.
def discos(request):
    lista_discos = Disco.objects.all()
    return render(request, "A_app/discos.html",
                  {"lista_discos": lista_discos})


def remeras(request):
    lista_remeras = Remera.objects.all()
    return render(request, "A_app/remeras.html",
                  {"lista_remeras": lista_remeras})


def libros(request):
    lista_libros = Libros.objects.all()
    return render(request, "A_app/libros.html",
                  {"lista_libros": lista_libros})


def nuevo_disco(request):
    if request.method == "POST":
        formulario = DiscoForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect("contenido:discos")
    else:
        formulario = DiscoForm()
    return render(request, "A_app/submit_disco.html", {"formulario": formulario})


def libro_nuevo(request):
    if request.method == "POST":
        formulario = LibroForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect("contenido:libros")
    else:
        formulario = LibroForm()
    return render(request, "A_app/submit_libro.html", {"formulario": formulario})


def remera_nueva(request):
    if request.method == "POST":
        formulario = RemeraForm(request.POST)
        if formulario.is_valid():
            formulario.save()
            return redirect("contenido:remeras")
    else:
        formulario = RemeraForm()
    return render(request, "A_app/submit_remera.html", {"formulario": formulario})


def busqueda_discos(request):
    buscar = request.GET.get("q", "")
    resultados = []
    if buscar:
        encontrado = Disco.objects.filter(artista__icontains=buscar)
        if encontrado.exists():
            resultados.append(("Disco", encontrado))
    return render(request, "A_app/resultados.html", {"resultados": resultados})

A_Main/templates/A_Main/index.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <title>Pagina {% block title %} {% endblock title %}</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/style_index.css' %}" />
    <link
      rel="icon"
      type="image/icon"
      href="{% static 'css/images/icono_01.png' %}"
    />
  </head>
  <body>
    <header>
      <h2 class="logo">
        <a href="{% url 'Main:index' %}"> Web con Django </a>
      </h2>
      <nav class="navi">
        <a href="{% url 'contenido:discos' %}">Discos</a>
        <a href="{% url 'contenido:libros' %}">Libros</a>
        <a href="{% url 'contenido:remeras' %}">Remeras</a>
      </nav>
    </header>
    <main>{%block content%} {% endblock %}</main>
  </body>
</html>

A_app/templates/A_app/discos.html
{% extends 'A_Main/index.html' %} 
{% block title %}| Discos {% endblock %} 
{%block content %}
    <ul style="list-style-type: none; padding: 0;">
        <form method="GET" action="{% url 'contenido:resultados' %}" style="text-align: center; padding: 15px;">
            <input type="text" name="q" placeholder="Buscar por artista" autocomplete="off" style="color: lightsteelblue; padding: 8px; width: 300px; text-align: center; border: none; background: transparent; outline: none;">
            <button class="busc" type="submit">Buscar</button>
        </form>
        <h1 class="titulo_disc">
            <a href="{% url 'contenido:agg_disco' %}" style="user-select: none; text-decoration: none; color: lightsteelblue; text-shadow: -1px 1px 0 black;">
                Música
            </a>
        </h1>
        {% for cd_list in lista_discos %}
            <li style="padding: 10px; padding-top: 9%; border-bottom: 1px solid #ccc; text-align: center;">
                {{cd_list.nombre}} - {{cd_list.artista}} - {{cd_list.year}}</li>
        {% endfor %}
    </ul>
{% endblock %}

A_app/templates/A_app/libros.html
{% extends 'A_Main/index.html' %}
{% block title %}| Libros {% endblock %} 
{%block content %}
    <ul style="list-style-type: none; padding: 0;">
        <h1 style="text-align: center; padding-top: 9%; text-decoration-line: overline; text-decoration-color: lightsteelblue;"> 
            <a href="{% url 'contenido:agg_libro' %}", style="user-select: none; text-decoration: none; color: lightsteelblue; text-shadow: -1px 1px 0 black;">
                Libros
            </a>
        </h1>
        {% for libro_list in lista_libros %}
            <li style="padding: 10px; padding-top: 9%; border-bottom: 1px solid #ccc; text-align: center;">
                {{libro_list.titulo}} - {{libro_list.autor}} - {{libro_list.year}}</li>
        {% endfor %}
    </ul>
    
{% endblock %}

A_app/templates/A_app/remeras.html
{% extends 'A_Main/index.html' %}
{% block title %}| Remeras {% endblock %}
{%block content %}
    <ul style="list-style-type: none; padding: 0;">
        <h1 style="text-align: center; padding-top: 9%; text-decoration-line: overline; text-decoration-color: lightsteelblue;">
            <a href="{% url 'contenido:agg_remera' %}" style="user-select: none; text-decoration: none; color: lightsteelblue; text-shadow: -1px 1px 0 black;">
                Remeras
            </a>
        </h1>
        {% for shirt_list in lista_remeras %}
            <li style="padding: 10px; padding-top: 9%; border-bottom: 1px solid #ccc; text-align: center;">
                {{shirt_list.disenio}} - {{shirt_list.talle}}
            </li>
        {% endfor %}
    </ul>
{% endblock %}

A_app/templates/A_app/resultados.html
{% extends 'A_Main/index.html' %} 
{% block title %}| Discos {% endblock %} 
{%block content %}
    {% if resultados %}
        <ul style="text-align: center;">
            <h2 style="text-align: center;padding-top: 50px; padding-bottom: 10px; text-decoration-line: underline;">Resultados de Busqueda</h2> 
            {% for model_name, discos in resultados %}
                <ul>
                    {% for disco in discos %}
                        <li>{{ disco.nombre }} - {{ disco.year }}</li>
                    {% endfor %}
                </ul>
            {% endfor %}
        </ul>
    {% else %}
        <div>
            <h2 style="text-align: center; margin-top: 50px;">Resultados de Busqueda</h2>
            <h3 style="text-align: center; margin-top: 50px;">Sin resultados.</h3>
            <button>Volver a Discos</button>
        </div> 
    {% endif %}
{% endblock %}

A_app/templates/A_app/submit_disco.html
{% extends 'A_Main/index.html' %} 
{% block title %}| NUevo Disco {% endblock %} 
{%block content %}
    <form method="post" style="text-align: center">
        {% csrf_token %}
        <p style="padding-bottom: 50px;">{{ formulario }}</p>
        <button type="submit" style="font-size: 30px; font-weight: bolder; font-style: italic; margin-top: 15%; cursor: default; user-select: none; text-decoration: none; color: lightsteelblue; text-shadow: -1px 1px 0 black; background: none;border: none;">
            Subir Disco</button>
    </form>
{% endblock %}

A_app/templates/A_app/submit_libro.html
{% extends 'A_Main/index.html' %} 
{% block title %}| Libro Nuevo {% endblock %} 
{%block content %}
    <form method="post" style="text-align: center">
        {% csrf_token %}
        <p style="padding-bottom: 50px;"> {{ formulario }} </p>
        <button type="submit" style="font-size: 30px; font-weight: bolder; font-style: italic; margin-top: 15%; cursor: default; user-select: none; text-decoration: none; color: lightsteelblue; text-shadow: -1px 1px 0 black; background: none;border: none;">
            Subir Libro</button>
    </form>
{% endblock %}

A_app/templates/A_app/submit_remera.html
{% extends 'A_Main/index.html' %}
{% block title %}| Nueva Remera {% endblock %}
{%block content %}
    <form method="post" style="text-align: center">
        {% csrf_token %}
        <p style="padding-bottom: 60px;">{{ formulario }}</p>
        <button type="submit" style="font-size: 30px; font-weight: bolder; font-style: italic; margin-top: 15%; cursor: default; user-select: none; text-decoration: none; color: lightsteelblue; text-shadow: -1px 1px 0 black; background: none;border: none;">
            Subir Remera</button>
    </form>
{% endblock %}